name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: Lint, Format, and Test
    runs-on: ubuntu-latest

    env:
      EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.EXPO_PUBLIC_SUPABASE_URL }}
      EXPO_PUBLIC_SUPABASE_KEY: ${{ secrets.EXPO_PUBLIC_SUPABASE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check TypeScript
        run: npx tsc --noEmit

      - name: Check formatting
        run: npx prettier --check "**/*.{js,jsx,ts,tsx,json,md}"

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Validate Expo config
        run: npx expo-doctor

      - name: Test export bundle
        run: npx expo export --platform all --output-dir dist
